{{- if .Values.backups.objectStorage.endpointCA.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-backup-ca-bundle" (include "cluster.fullname" .) }}
data:
  {{ .Values.backups.objectStorage.endpointCA.key }}: {{ .Values.backups.objectStorage.endpointCA.value }}
{{- end }}
